### ISSUE TITLE
公共 CDN 资源

### ISSUE THREAD

**Issue by FeiYuab** [bs-community/blessing-skin-manual#10]
CDN是cloudflare的Enterprise 开启中国网络 全球都有节点
资源列表 版本4.4.0-5.0.0-beta9 并且会更新
https://s1.pangdidi.cn/CDN/blessing-skin-server/cdn.json

**Comment by FeiYuab** [comment]
修改下描述:
CloudFlare 的 Enterprise 套餐，并开启中国网络，全球都有节点。
地址: https://s1.pangdidi.cn/CDN/blessing-skin-server/:version/public
请将地址中的 `:version` 替换为皮肤站当前所使用的版本。[支持的版本](https://s1.pangdidi.cn/CDN/blessing-skin-server/versions.json)

**Comment by g-plane** [comment]
https://github.com/bs-community/blessing-skin-manual/commit/5da8c226695d78f201b278d12428833dcecf1890
