### ISSUE TITLE
新增更新源

### ISSUE THREAD

**Issue by Nofated095** [bs-community/blessing-skin-manual#14]
利用jsdelivr搭建的更新源
手动维护，经过测试4.4.0成功升级5.0.0

更新源1 <https://cdn.jsdelivr.net/gh/Nofated095/bsswh@master/update.json>

![](https://i.loli.net/2020/08/10/tpsViIBgPvwAyaW.png)

**Comment by g-plane** [comment]
BS 的压缩包通常不少于 10 MB，这样做是在滥用 jsDelivr。
