### ISSUE TITLE
authlib-injector.jar在客户端的哪个位置..

### ISSUE THREAD

**Issue by axin0452** [bs-community/blessing-skin-manual#16]
事情是这样的,因为反作弊识别md5码的关系,每次玩家从网页上拖拽api到启动器上,然后登陆进服以后的authlib-injector.jar都是不一样的,所以我想问一下这个文件的位置,看是否能用脚本给每个玩家更新相同的authlib-injector.jar文件..

**Comment by g-plane** [comment]
根目录是 .minecraft 文件夹。

**Comment by axin0452** [comment]
> [. minecraft]

在哪里我没有看到啊..可以说的在具体点吗 他是隐藏起来了吗

**Comment by g-plane** [comment]
你确定你是 Minecraft 玩家吗？

**Comment by g-plane** [comment]
另外我还没完全清楚你想遇到了什么问题，也不知道你是玩家还是服主。

**Comment by tnqzh123** [comment]
不同启动器有不同的策略。

比如，HMCL 会将 authlib-injector 保存到 `%appdata%/.hmcl/`，而不是游戏文件夹内。（除非你打开 HMCL 时加 JVM 参数指定 authlib-injector 的位置）

相关问题建议咨询启动器作者。

**Comment by axin0452** [comment]
> 不同启动器有不同的策略。
> 
> 比如，HMCL 会将 authlib-injector 保存到 `%appdata%/.hmcl/`（除非你打开 HMCL 时加 JVM 参数指定 authlib-injector 的位置）、BakaXL 会保存到同目录下的 `BakaXL` 目录内，而不是游戏文件夹内。
> 
> 相关问题建议咨询启动器作者。
>  
> 此外，一般情况下，各启动器下载到的 authlib-injector 都是一样的（版本不同除外），其各种 Hash 当然也是一样的，所以「每次玩家从网页上拖拽 API 到启动器上，然后登录进服以后的 authlib-injector.jar 都是不一样的」是 **不成立** 的。

![image](https://user-images.githubusercontent.com/39695561/90331848-6cdd3880-dfea-11ea-9e10-aea525bfe051.png)

虽然你说不成立但是我确实遇到了不同的 authlib-injector 开始加反作弊进行验证的时候 没有提示 我都搞不懂为啥玩家进不去服务器 后来加了 cac反作弊 他有反作弊的提示 我才知道 是authlib-injector的原因

**Comment by tnqzh123** [comment]
@axin0452 请咨询启动器作者。
