### ISSUE TITLE
Web API 的登陆接口没有返回token

### ISSUE THREAD

**Issue by James318** [bs-community/blessing-skin-manual#25]
post测试/api/auth/login接口返回{"JWT":""}

**Comment by g-plane** [comment]
可以说说你这个请求的完整信息吗？包括 body 以及头部信息等。

**Comment by James318** [comment]
Ip: 106.15.251.97
Request URL: https://skin.dreamclouds.top/api/auth/login
Request Method: POST
Status Code: 200 OK
Request Proto: HTTP/1.1
Request Header
Content-Type:application/json;
Response Header
Connection:keep-alive;
Date:Mon, 28 Dec 2020 07:18:48 GMT;
Set-Cookie:locale=zh_cn; expires=Mon, 28-Dec-2020 09:18:48 GMT; Max-Age=7200; path=/; httponly; samesite=lax;
Server:nginx;
Content-Type:application/json;
Cache-Control:no-cache, private;
X-Ratelimit-Limit:60;
X-Ratelimit-Remaining:59;
X-Authlib-Injector-Api-Location:https://skin.dreamclouds.top/api/yggdrasil;
Strict-Transport-Security:max-age=31536000;

post过去的数据：{"email":"411309583@qq.com"
,"password":"TOPcok0313"}

**Comment by g-plane** [comment]
v6 因兼容性不再支持 JWT 方式登录，请改用 OAuth2。
