### ISSUE TITLE
无法正常进入皮肤站 提示"No input file specified."

### ISSUE THREAD

**Issue by CrabTechs** [bs-community/blessing-skin-manual#26]
报错如下图。
PHP版本：PHP-74
服务器使用环境：Apache
数据库：MySQL 5.7.28
使用Chrome，Edge，Firefox均会出现此类问题
出现问题时浏览器的URL是skin2-b.crabhouse.top
![image](https://user-images.githubusercontent.com/76773407/104020915-e32c4280-51f8-11eb-8618-37ab0c6342f1.png)

**Comment by CrabTechs** [comment]
https://s3.jpg.cm/2021/01/08/v7s1t.png

**Comment by tnqzh123** [comment]
这是你 Web 引擎和 PHP 没有配置好，并不是 BS 的问题。

**Comment by CrabTechs** [comment]
检查过了，配置木得问题

**Comment by CrabTechs** [comment]
然后原先没有的open_basedir被打开之后就不能用了

**Comment by CrabTechs** [comment]
注释了也不行

**Comment by g-plane** [comment]
出现这种问题肯定是配置不对。尝试排查以下问题：
- php 模块有没有正常加载？
- 有没有确保网站目录放在 `/home` 以外的地方？（推荐 `/srv`）
- 目录等的权限有没有正确设置？

有时候只是你觉得配置没有问题，但是服务器不是这么认为的。

**Comment by CrabTechs** [comment]
> 出现这种问题肯定是配置不对。尝试排查以下问题：
> 
> * php 模块有没有正常加载？
> * 有没有确保网站目录放在 `/home` 以外的地方？（推荐 `/srv`）
> * 目录等的权限有没有正确设置？
> 
> 有时候只是你觉得配置没有问题，但是服务器不是这么认为的。

正常加载，网站目录也不在home，用的宝塔，该取消禁用的参数全部取消了，权限都是755

**Comment by g-plane** [comment]
用宝塔啊……那请您自行研究。

**Comment by CrabTechs** [comment]
我换个PHP-80试试

**Comment by CrabTechs** [comment]
@g-plane 现在没有任何提示 错误码500

**Comment by CrabTechs** [comment]
![Uploading image.png…]()

**Comment by g-plane** [comment]
因为最新版 BS 还不支持 PHP 8。

**Comment by CrabTechs** [comment]
草

**Comment by Restent** [comment]
@CrabTechs GPlane 只是说尽快支持 PHP 8，还没说完全支持。

**Comment by CrabTechs** [comment]
az

**Comment by g-plane** [comment]
这跟你当前的问题没有任何关系。

**Comment by CrabTechs** [comment]
那我就关闭Issues了

**Comment by CrabTechs** [comment]
感谢
