### ISSUE TITLE
输入框消失了

### ISSUE THREAD

**Issue by CrabTechs** [bs-community/blessing-skin-manual#27]
![image](https://user-images.githubusercontent.com/76773407/104081291-a26c1200-5268-11eb-9def-ed4d4b323a42.png)
![image](https://user-images.githubusercontent.com/76773407/104081302-b748a580-5268-11eb-830c-1ff61ec1ef4d.png)
注册登录页面的输入框消失了，并且部分样式丢失

**Comment by g-plane** [comment]
请您认真按手册上的指导来配置服务器。如果在部署中遇到问题，建议加入我们的 Telegram 群组或 Discord 社区。
