### ISSUE TITLE
api可以用了但是服务端authlib-injector不能用

### ISSUE THREAD

**Issue by 3186418613** [bs-community/blessing-skin-manual#30]
[ERROR] Failed to fetch metadata: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by yushijinhun** [comment]
请确认服务器 HTTPS 证书链是否完整。

**Comment by g-plane** [comment]
长时间没有反馈，现关闭 issue。
