### ISSUE TITLE
需求 通过角色名返回皮肤png格式文件的接口

### ISSUE THREAD

**Issue by RuofengX** [bs-community/blessing-skin-manual#35]
Dynmap插件需要通过角色名获取skin来制作头像，需要一个输入角色名即返回角色对应皮肤的png文件的接口。
api文档中没有这类接口。
P.S.注意到有“传统皮肤加载方式”这一插件，能否满足要求？安装后如何实现？

**Comment by mochaaP** [comment]
@RuofengX 传统皮肤加载方式可以实现，请参阅插件文档。

**Comment by RuofengX** [comment]
很难找到插件的api文档

**Comment by mochaaP** [comment]
<https://github.com/bs-community/blessing-skin-plugins/blob/master/plugins/legacy-api/bootstrap.php#L9>

`<皮肤站地址>/skin/<玩家名>.png`
