### ISSUE TITLE
请问如何查询4.0版本的文档

### ISSUE THREAD

**Issue by asforest** [bs-community/blessing-skin-manual#39]
请问如何查询4.0版本的文档，因为环境限制，只能使用4.0版本，但我却找不到4.0版本的文档
在[blessing-skin-server](https://github.com/bs-community/blessing-skin-server/commit/777fc2315192da6c8781807669d90c85ef667d3e)项目的readme中，文档是指向wiki的，但是wiki内容又被移除掉了
另外在文档的网站，https://blessing.netlify.app/build.html，里也找不到明显的旧版本跳转链接。

**Comment by g-plane** [comment]
这个没有，因为文档没法按照不同版本来区分。

**Comment by asforest** [comment]
建议文档这边跟主项目同步发布Release，要用旧版本却找不到文档确实很头疼

**Comment by g-plane** [comment]
这个解决不了问题，因为现在最新的是 5.x 了，文档还是不会有 4.x 甚至是 4.0 的内容。但可以通过翻看 Git 的记录来查找以前的内容。

**Comment by asforest** [comment]
好的，感谢回复
