### ISSUE TITLE
提供两个更新源

### ISSUE THREAD

**Issue by kasuganosoras** [bs-community/blessing-skin-manual#4]
解决部分地区无法下载 Azure 文件的问题，长期提供更新服务

- 宿迁服务器：https://cmi.zerodream.net/bss/
- 美国服务器：https://cdn.worldofcraft.cn/bss/

两个源均会跟随官方版本更新

**Comment by tnqzh123** [comment]
@kasuganosoras 要不要加个描述啥的？

**Comment by kasuganosoras** [comment]
@tnqzh123 emmmm... 描述的话，这个吧……
> 更新服务器由 [ZeroDream](https://www.zerodream.net/) 提供
>
> - 国内服务器位于江苏宿迁，中国移动宽带，100Mbps 对等网络
> - 国外服务器位于美国堪萨斯，使用 CloudFlare 加速，1Gbps 对等网络
>
> 文件的更新频率为每天一次，保持和官方 Azure 仓库同步
>
> 爱发电：https://afdian.net/@Akkariin

**Comment by Cinnamoroll-cat** [comment]
证书失效了，我这是每周一次，长期提供更新服务，同时也会提供下载服务等，地址：[https://update.snowflake.moe/blessing-skin/](地址)，update是更新服务，download是下载服务。

**Comment by Cinnamoroll-cat** [comment]
证书失效了，我这是每周一次，长期提供更新服务，同时也会提供下载服务等，地址：[地址](https://update.snowflake.moe/blessing-skin/)，update是更新服务，download是下载服务。

**Comment by kasuganosoras** [comment]
新的镜像站地址：https://static-cdn.zerodream.net/bss/

重新搭建新的更新源了，并且重写了更新服务器，源码也已经开源：https://github.com/kasuganosoras/bss-update

```
https://static-cdn.zerodream.net/bss/{channel}/{version}/{subversion}/{build}
```
其中可选参数（不带任何参数则默认是稳定构建最新版）：
- channel 更新通道，可以是 `stable`，`rc`，`beta`, `alpha`
- version 主要版本号，目前有 `4`，`5`，`6`
- subversion 详细版本号，例如 `5.2.0`
- build 构建编号，例如 `1`，对应的就是 `6.0.0-rc.1` 中的最后一位

如果不带任何参数，则默认 channel 为 `stable`，version 为 `5`。
