### ISSUE TITLE
皮肤库分类切换

### ISSUE THREAD

**Issue by DongShaoNB** [bs-community/blessing-skin-manual#41]
前提:皮肤库中皮肤分类有2页，其他(Steve,Alex,披风)等中有一个分类只有1页
实现方法:首先切换到皮肤分类，然后选择第2页，再切换分类到只有1页的分类就会显示无结果
建议切换分类后自动跳转到该分类的第1页
(BUG，但不完全是BUG

**Comment by g-plane** [comment]
请勿重复创建 issue（https://github.com/bs-community/blessing-skin-server/issues/362 ）。Blessing Skin 本身的 bug 请在 [bs-community/blessing-skin-server](https://github.com/bs-community/blessing-skin-server) 提。
