### ISSUE TITLE
开启正版验证插件之后，正版用户登录时显示”用户不存在“

### ISSUE THREAD

**Issue by LIHAOCHI** [bs-community/blessing-skin-manual#43]
PHP版本：8.0
Web服务器：Nginx
你用的什么数据库：MySQL
浏览器：Chrome
出现问题时浏览器地址栏上的URL：https://lhmc.club/auth/login

错误截屏：
[https://raw.githubusercontent.com/LIHAOCHI/Pictures/master/Screenshot%202022-02-06%20131801.png](url)

出现错误时皮肤站日志laravel文件的信息为：

> [2022-02-06 13:23:16] production.WARNING: Received unexpected HTTP status code from Mojang server: 403

**Comment by Big-Cake-jpg** [comment]
@LIHAOCHI 开错地方了，请去 blessing-skin-plugins 仓库
