### ISSUE TITLE
我有多个更新源

### ISSUE THREAD

**Issue by Cinnamoroll-cat** [bs-community/blessing-skin-manual#44]
我的官网有很多个blessing-skin的更新源，请问能不能全都添加到[更新源列表](https://blessing.netlify.app/update-sources.html#第三方更新源)上面。
永远都是最新的更新源：https://update.snowflake.moe/blessing-skin/update/update.json
永远停留在正式版的更新源：https://update.snowflake.moe/blessing-skin/update/update-official.json
永远停留在beta版的更新源：https://update.snowflake.moe/blessing-skin/update/update-beta.json
永远停留在rc版或dev版的更新源：https://update.snowflake.moe/blessing-skin/update/update-dev.json

**Comment by g-plane** [comment]
#45
