### ISSUE TITLE
维护第三方更新源

### ISSUE THREAD

**Issue by Blank038** [bs-community/blessing-skin-manual#51]
程序自动 clone 仓库文件(Blessing Skin Server)
最新版(拉取到的)：https://cdn.mc9y.com/bs/update.json
旧版(曾经被拉取过的)：[https://cdn.mc9y.com/bs/{version}/update.json](https://cdn.mc9y.com/bs/%7Bversion%7D/update.json)
(此项未完工本地 update.json 文件生成，有空了修改下程序代码)

**Comment by g-plane** [comment]
旧版的链接访问不了？

**Comment by Blank038** [comment]
> 旧版的链接访问不了？

已修复并更新了代码，之前没有完工这部分的代码，每 15 分钟会拉取一次更新。
旧版只能获取到曾经拉取到的，目前仅：6.0.0-beta.3、6.0.0-beta.4、6.0.0-rc.1、6.0.0-rc.2
