### ISSUE TITLE
CDN地址更新

### ISSUE THREAD

**Issue by hempflower** [bs-community/blessing-skin-manual#7]
CDN地址: `https://bs-mirror.i-creator.cn/:version/public`    
其中`:version`替换成BS版本号。目前此CDN地址适用于以下版本:
- 4.0.4
- 4.1.0
- 4.1.1
- 4.1.2
- 4.1.3
- 4.1.4
- 4.2.0
- 4.2.1
- 4.3.6
- 4.4.0

替换后的地址应类似于: `https://bs-mirror.i-creator.cn/4.0.4/public`

**Comment by tnqzh123** [comment]
要不要再加一个 CDN 描述？

PS：可以直接发 PR

**Comment by hempflower** [comment]
CDN描述:
> 此CDN由[OreCraft](http://www.orecraft.cn)提供。 如果此CDN对您有帮助，可以通过[爱发电](https://afdian.net/@hempflower)打赏。
>
> 如果在CDN支持的版本中没有找到您需要的，您可以联系QQ：1993996310更新。
