### ISSUE TITLE
新公共CDN提交

### ISSUE THREAD

**Issue by TheBaiRuo** [bs-community/blessing-skin-manual#8]
https://bs-mirrors.bairuo.top/

https://bs-mirrors.bairuo.top/:verison/public/app

支持
4.4.0
4.3.6
4.2.1
4.2.0
4.1.4
4.1.3
4.1.2
4.1.1
4.1.0
4.0.4
4.0.3
4.0.2
4.0.1
4.0.0

由白渃提供https://blog.bairuo.top

Q：3337980633添加时注明Blessing Skin

i发电：https://afdian.net/@TheBaiRuo

**Comment by g-plane** [comment]
我这边访问不了 https://bs-mirrors.bairuo.top/4.4.0/public/app/manifest.json 这个链接。

**Comment by tnqzh123** [comment]
@g-plane

> 我这边访问不了 https://bs-mirrors.bairuo.top/4.4.0/public/app/manifest.json 这个链接。

我这边没问题？

![Screenshot_2020-03-31-22-57-26-359_com.android.chrome.jpg](https://i.loli.net/2020/03/31/9bCWkivxLVwZDIX.jpg)

**Comment by g-plane** [comment]
用 curl 试了下，确实可以，可能是浏览器的问题。

**Comment by TheBaiRuo** [comment]
我用浏览器也是可以的，可能卡了啥BUG
