### ISSUE TITLE
非官方的仓库

### ISSUE THREAD

**Issue by Nofated095** [bs-community/blessing-skin-manual#9]
## Gitee维护仓库

emmm，我心血来潮，在Gitee做了一个[镜像站](https://gitee.com/nofated/blessing-skin-server)，还有一个编译版[仓库](https://nofated.gitee.io/blessing-skin-server/)，可以考虑把这个镜像站放在releases吗？

我以后会考虑再做一个更新源

**Comment by g-plane** [comment]
如果你建好了更新源，可以在这里说一声。

**Comment by Nofated095** [comment]
Emmmm，搭建好了
(update.json)[https://gitee.com/nofated/blessing_skin_server_warehouse/raw/master/update.json]
目前json的指向地址是位于gitee仓库编译好的beta8，可是为什么我老是觉得我做错了呢？我看好像别人更新源都是无法访问编译好的文件的

**Comment by Asnxthaony** [comment]
![image](https://user-images.githubusercontent.com/12845643/79942320-255dfa00-8499-11ea-8d43-4829fd8ba9e1.png)
更新源无法在非登录的情况下使用。

**Comment by g-plane** [comment]
长时间未收到回复。
